### ISSUE TITLE
[VT-90] Update display after sync

### ISSUE THREAD

**Issue by taskwarrior** [scottkosty/vit#112]
_Jochen Sprickerhof on 2014-06-12T07:25:41Z says:_ 

 Currently task are not reread after syncing with taskd. The attached patch fixes this.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-06-12T07:25:41Z
Modified: 2015-03-01T23:43:00Z
```

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2015-03-01T00:59:25Z says:_ 

 Thank you for this bug report. I just took a quick look at your patch. From what I understand, you suggest a reread after ever character input. I don't think this is correct. I think we can fix this bug in a more simple way, but just rereading after syncing. I will look into this for 1.3.

**Comment by taskwarrior** [comment]
_Jochen Sprickerhof on 2015-03-01T17:09:47Z says:_ 

 Putting the reread_needed after the &shell_exec("task sync" should be fine as well. Thanks for coming back to this.

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2015-03-01T23:42:00Z says:_ 

 I actually misread the patch on my quick look. Yes, I do like putting it after the shell_exec. It reads better and is more efficient. I just committed to 117255b2 (on branch 1.3). Thank you for the report and patch. You're in the AUTHORS file. Note that I kept the refresh_needed that you removed. It is necessary (otherwise the error is not shown because the screen is not refreshed).

**Comment by pbeckingham** [comment]
[VT-90_0001-Update-display-after-sync.patch.txt](https://github.com/scottkosty/vit/files/1755280/VT-90_0001-Update-display-after-sync.patch.txt)

**Comment by ryanerwin** [comment]
Hello, I'm using what I think is the current version of `vit` that would include the re-read after sync, but I noticed my `vit` window is still not updating (new tasks synced from inthe.am aren't shown in vit).

I'm using: `vit 1.3.dev (96134b3)`

Is there something else I need to setup so that synced tasks will show?

Normally I get task updates via a `task sync` in `chron.hourly`.

**Comment by scottkosty** [comment]
@ryanerwin that is indeed the good build to use. I think you might be looking for something like #151. VIT supports sync only in the sense that it binds "s" to "task sync".
